### ISSUE TITLE
Update example code in documentation

### ISSUE THREAD

**Issue by ShehriyarQureshi** [lipanski/mockito#126]
The code in the [first example](https://docs.rs/mockito/0.26.0/mockito/#example)

```rust
#[cfg(not(test))]
let url = "https://api.twitter.com";
```

 gives a compiler error `expected item after attributes` (also raised in issue #122 ).

I fixed it by replacing the `let` statement with a `const` one. If this is the right way to do it, the documentation should be updated with the correct code.

**Comment by lipanski** [comment]
@ShehriyarQureshi thanks for reporting this. I updated the documentation by adding an explicit `fn main { ... }` around the code: https://github.com/lipanski/mockito/commit/9f74586473ed361bdee7e20fa5f1ed82fbc9c681

do note that [Rust wraps doc tests](https://doc.rust-lang.org/rustdoc/documentation-tests.html#pre-processing-examples) inside `fn main { ... }` by default so that's kind of implied when reading Rust docs (except when there is an explicit `fn main {}` call). that's also why my doc tests would pass with this code.

in any case, you are still free to move these declarations outside of `fn main { ... }` or simply pass `mockito::server_url()` to your client during tests (if your client exposes a method to set the base URL).
