### ISSUE TITLE
Mockito doesn't seem to notice requests from a child thread. 

### ISSUE THREAD

**Issue by nathanaeljones** [lipanski/mockito#26]
```
Fetched http://127.0.0.1:1234/v1/licenses/latest/testda42e8a40db14c091dea84efd572933fdfe31ba9620e5fee79edb823a448b6e8.txt`

thread 'licensing::test::test_remote_license_success' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: 
Expected 1 request(s) to:

GET /v1/licenses/latest/testda42e8a40db14c091dea84efd572933fdfe31ba9620e5fee79edb823a448b6e8.txt

...but received 0
```

**Comment by nathanaeljones** [comment]
And I get a 501 when I shouldn't, as well. 

Any idea what could be going on?

**Comment by nathanaeljones** [comment]
I didn't run into this when I was operating on a single thread.

**Comment by lipanski** [comment]
I'll have a look.

**Comment by lipanski** [comment]
@nathanaeljones I've added a test [here](https://github.com/lipanski/mockito/commit/0908ef34f0d1dc5d1bb7111ac92f3dbd844c1607) but it seems to be working fine.

could you go into a bit more detail? maybe write a test that fails and I'll pick it up from there?

here are some possible problems that you could check against, otherwise I'd need more details:

(1) the mock's lifetime: as explained [here](http://lipanski.github.io/mockito/generated/mockito/index.html#lifetime), you'll need to assign your mock to a variable. the lifetime of the variable controls the lifetime of the mock.

(2) not waiting for the thread to finish (before checking that the mock matched) - e.g. call `.join()`

**Comment by lipanski** [comment]
(3) avoid assigning your mock to a variable called `_`, use something like `_m` or `_mock` or whatever as long as there's not just the *underscore* - reported [here](https://github.com/lipanski/mockito/issues/27) and now part of the docs
