### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by mikeastock** [lipanski/mockito#3]
Are you interested in getting Travis-CI setup for this project? If so I'll gladly help set it up.

**Comment by lipanski** [comment]
Just set it up in #5 

Some of the doc tests were flickering (mainly because of the shared state of the mock server) so I had to test it with `cargo test -- --test-threads=1`.

I realise that some use-cases might show a similar problem, in which case `--test-threads=1` should do the job. However, this does slow down your tests a bit.

I've made a mental note to fix this here: https://github.com/lipanski/mockito/issues/6
