### ISSUE TITLE
Record requests

### ISSUE THREAD

**Issue by dbrgn** [lipanski/mockito#67]
Is there a way to access the requests on a mock instance?

If not, that would be a great feature to have :)

**Comment by lipanski** [comment]
@dbrgn well technically it would be fairly easy to expose [the STATE](https://github.com/lipanski/mockito/blob/master/src/server.rs#L55) which holds all the mocks. it's a mutex so accessing it might be a bit more painful, but not impossible. however, I'd rather keep these internals private to avoid complicating things. the only way I'd expose it is via a polished read-only interface (so not the whole `STATE`), but I'm not sure if it's worth it.

could you explain your use case - maybe there's some other way around this.

**Comment by dbrgn** [comment]
My main goal would be to assert that the correct payload (and maybe also the correct headers) were sent in the request.

Maybe allowing readonly access to request payload and headers might be an option?

**Comment by lipanski** [comment]
@dbrgn isn't this problem solved by [matchers](https://docs.rs/mockito/0.17.1/mockito/#matchers)? for example, if you'd like to make sure your request headers were matched - I'd set the `match_header` function when creating the mock. in order to match the request body, you can use `match_body`. both methods accept the different style of matchers (strict, regex, json etc.). requests that don't have these headers/body will simply not be matched and will fail when calling `Mock#assert()`.

does this solve your problem?

**Comment by dbrgn** [comment]
@lipanski sorry for the late answer. Yep, that looks like it'll solve my problem :slightly_smiling_face:
