### ISSUE TITLE
"501 Not Implemented" on mockito 0.20 when mock not found 

### ISSUE THREAD

**Issue by apiraino** [lipanski/mockito#83]
Hi!

I managed to produce a weird error. After a long debugging session I think that it is my fault, but still I find that the error reporting confusing and - most importantly - I did not have this issue with `mockito = 0.19`.

I run my integration tests in a separate crate. The mockito instance is created in the tests crate with `mockito:start()`, the crate return the mocked URL address.

When I go back to my backend library, in the `/test` directory, I mock a request with `mockito::mock()...create()` and I try to use the URL returned by the mocked HTTP client but I receive this 501 error.

I suspect this has to do with this [state](https://github.com/lipanski/mockito/blob/f1c588113ae57cb41ebde939dd33c70f61431e10/src/server.rs#L45) management but could not figure out what changed from 0.19 to 0.20 to trigger this issue.

Besides, I could not find any explicit usage of the `Status::NotImplemented`.
(EDIT: I suspect I'm getting a "Mock Not Found" error with just a wrong label)

Hope my explaination (without any code snippets) is clear enough!

Thanks if you can share an opinion on this

**Comment by calvinlauco** [comment]
Not sure if it is the same problem as yours, but you have to assign the result of `mock(..).create()` to a variable as described in the example:
```
let _m = mock(...).create();
```

The reason is when the mock get dropped, it clears all the `mocks` in `state`. So you have to assign it to a placeholder to avoid the variable get dropped before you request.

I think it should state more clearly the importance of keeping the result in the documentation (or maybe I miss it somehow).

**Comment by lipanski** [comment]
@apiraino sorry for the late reply. is this still an issue? would you be able to explain how to reproduce this in more detail? maybe with some code (simplified)? otherwise I can't really help much.

the possible reason why you're getting `501 Not Implemented` instead of `501 Mock Not Found` is that some HTTP clients might be parsing the status code only and fetching the status text by matching the status code to a known list, but this is just an assumption.

**Comment by apiraino** [comment]
Hi @lipanski thanks for the reply. In the end I've replaced mockito with a man-in-the-middle proxy to mock my integration tests. If I have a chance, I'll get back to it and try harder to provide a useful test case :)
Meanwhile I'll close this issue so it won't hang around. I can always reopen it in the future.
