### ISSUE TITLE
Code coverage with tarpaulin

### ISSUE THREAD

**Issue by valnoel** [lipanski/mockito#84]
Hello!

I'm trying to integrate mockito in some unit tests for the [rs_amqp_worker](https://github.com/media-cloud-ai/rs_amqp_worker) project (see the related [PR](https://github.com/media-cloud-ai/rs_amqp_worker/pull/9)), and I cannot get through the code coverage computed with [tarpaulin](https://github.com/xd009642/tarpaulin).

My issue is that the coverage randomly fails (on [Travis](https://travis-ci.org/media-cloud-ai/rs_amqp_worker/builds/574789179) and locally) running one of the unit tests that uses mockito (only them). It's not always the same test that makes it fail, and sometimes the coverage completes correctly.

I suspected a concurrent issue due to the static `mockito::server_url()`, but I tried some workaround (distributing my mocks on different HTTP resources) but it doesn't change anything.

However, I have no problem executing a multi-threaded `cargo test` on the project.

Would you have any idea on how to fix this? Thanks!

**Comment by lipanski** [comment]
I'm not familiar with tarpaulin or how it's built but one thing to note is that Mockito tests are actually [run sequentially](https://github.com/lipanski/mockito/blob/f1c588113ae57cb41ebde939dd33c70f61431e10/src/lib.rs#L948) - not in parallel. this is handled internally via a [thread_local mutex](https://github.com/lipanski/mockito/blob/f1c588113ae57cb41ebde939dd33c70f61431e10/src/lib.rs#L505). the mutex is there to allow all non-mockito tests to still run in parallel. given the current architecture, it was not possible to run Mockito tests in parallel at all, hence all this.

it could be that tarpaulin is somehow getting stuck on the mutex (in which case the test would timeout). but as I see in your Travis build, the only hint at the error is a "segfault". could you try to narrow this down - maybe run the tool in debug mode, to produce a more detailed error message?

you could also try raising the issue on the tarpaulin side or checking their other [segfault issues](https://github.com/xd009642/tarpaulin/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+segfault). I'm not saying that Mockito might not be the culprit here, but maybe they have an idea of what exactly might cause this.

**Comment by lipanski** [comment]
should probably be fixed by one of the recent releases https://github.com/lipanski/mockito/releases (0.32+)
